In [1]:
import numpy as np

In [2]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
#universal functions are basic functions that you can apply to every value of
#an array (example: square roots)
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [4]:
#can take an exponential of every value (e^each array value)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [6]:
#binary functions which require two arrays
#random.randn creates a random normal distribution of random numbers
A = np.random.randn(10)
B = np.random.randn(10)


In [8]:
A

array([ 0.01883673,  1.38293997,  1.1398531 ,  0.04397227,  1.21616381,
        0.4961912 ,  0.09566762, -1.74230708,  0.7440398 ,  1.41106541])

In [9]:
B

array([ 0.25558058, -0.30184514, -0.97142433, -1.01386242, -1.39223138,
       -0.32968198,  2.05094012, -0.51893583, -0.20860901,  1.51739557])

In [7]:
#binary function example
np.add(A,B)

array([ 0.27441731,  1.08109482,  0.16842876, -0.96989014, -0.17606757,
        0.16650922,  2.14660774, -2.26124291,  0.53543079,  2.92846098])

In [10]:
#ouput the maximum of two arrays
np.maximum(A,B)

array([ 0.25558058,  1.38293997,  1.1398531 ,  0.04397227,  1.21616381,
        0.4961912 ,  2.05094012, -0.51893583,  0.7440398 ,  1.51739557])

In [11]:
#can open a website on jupyter notebooks via the following
#the following link takes you to all the universal functions for numpy
website = 'https://docs.scipy.org/doc/numpy/reference/ufuncs.html'
import webbrowser
webbrowser.open(website)

True