In [10]:
import numpy as np

In [17]:
arr = np.arange(10,100,10)

In [18]:
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [19]:
arr[3]

40

In [20]:
arr[2:9]

array([30, 40, 50, 60, 70, 80, 90])

In [21]:
arr[0:5] = 100

In [22]:
arr

array([100, 100, 100, 100, 100,  60,  70,  80,  90])

In [23]:
slice_of_arr=arr[0:6]

In [24]:
slice_of_arr

array([100, 100, 100, 100, 100,  60])

In [35]:
#to make a copy of an object so that manipulations to the copy object 
#don't effect the original object
arr_copy= arr.copy()

In [36]:
arr_copy

array([100, 100, 100, 100, 100,  60,  70,  80,  90])

In [37]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [38]:
arr_2d[1]

array([20, 25, 30])

In [39]:
arr_2d[1][1]

25

In [40]:
arr_2d[:2][1:]

array([[20, 25, 30]])